{
 "title": "Database Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Number Of Recipes",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT count(*)\nFROM Dishes\n" }
   ]
  },
  {
   "title": "Number of Users that Added Favorites",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(distinct clientId)\nFROM Favorite"
    }
   ]
  },
  {
   "title": "Most chosen favorites",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 18, "x": 3, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT d.title, count(*) as numberDishes\r\nFROM Favorite f INNER JOIN Dishes d on f.dishId = d.id \r\nGroup BY d.title \r\nORDER BY numberDishes DESC"
    }
   ]
  }
 ]
}