version: '3'
services:
  python-chatbot:
    build: .
    image: sandroscr.azurecr.io/python-chatbot-image:latest
    container_name: python-chatbot
    env_file:
      - .env    
    environment: 
      - MODE=polling
    domainname: "${DOMAIN}"
    ports:
        - "8443:8443"
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - grafana_network
networks:
  grafana_network:
        