version: '3'
services:
  python-chatbot:
    build: .
    image: python-chatbot-image
    image: sandroscr.azurecr.io/python-chatbot-image
    container_name: python-chatbot
    env_file:
      - .env    
    environment: 
      - MODE=webhook
    ports:
        - "8443:8443"
    Just
    volumes: 
      - "./:/app"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - petstore
    ports:
      - "4000:4000"