on: [push]
name: Chatbot_Deployment_Workflow

env:
  DEP_PATH: /requirements.txt

jobs:
    build-and-deploy:
        name: buildImage
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Git Checkout main branch'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
          
        - name: Security vulnerabilities scan
          uses: aufdenpunkt/python-safety-check@master

        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: sandroscr.azurecr.io
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t sandroscr.azurecr.io/python-chatbot-image:${{ github.sha }}
            docker push sandroscr.azurecr.io/python-chatbot-image:${{ github.sha }}